In [1]:
list1=[3,4,6,7]
print(list1)

[3, 4, 6, 7]


In [3]:
import numpy as np
arr=np.arange(6)
%time print(arr)

[0 1 2 3 4 5]
CPU times: user 1.09 ms, sys: 65 µs, total: 1.16 ms
Wall time: 34.3 ms


In [5]:
list2=list(range(6))
print(list2)
%time print(list2)


[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5]
CPU times: user 69 µs, sys: 4 µs, total: 73 µs
Wall time: 64.1 µs


In [6]:
array1=np.array([3,2,5,1])
array1

array([3, 2, 5, 1])

In [7]:
print(type(array1))


<class 'numpy.ndarray'>


In [8]:
array2=np.array([[2,5,8,9],[8,6,5,8]])
array2

array([[2, 5, 8, 9],
       [8, 6, 5, 8]])

In [9]:
print(type(array2))


<class 'numpy.ndarray'>


In [10]:
array1.shape

(4,)

In [11]:
array2.shape

(2, 4)

In [12]:
array2.dtype

dtype('int64')

In [13]:
array1.dtype

dtype('int64')

In [14]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.zeros((7,7)).dtype

dtype('float64')

In [24]:
arr1=np.array([[8,9,5,6],[9,5,6,4]])
arr1

array([[8, 9, 5, 6],
       [9, 5, 6, 4]])

In [25]:
arr2=np.array([[8,7,1,4],[8,9,5,4]])
arr2

array([[8, 7, 1, 4],
       [8, 9, 5, 4]])

In [26]:
arr1+arr2

array([[16, 16,  6, 10],
       [17, 14, 11,  8]])

In [27]:
arr1-arr2

array([[ 0,  2,  4,  2],
       [ 1, -4,  1,  0]])

In [29]:
arr1*arr2

array([[64, 63,  5, 24],
       [72, 45, 30, 16]])

In [30]:
arr1/arr2

array([[1.        , 1.28571429, 5.        , 1.5       ],
       [1.125     , 0.55555556, 1.2       , 1.        ]])

In [31]:
arr1//arr2

array([[1, 1, 5, 1],
       [1, 0, 1, 1]])

In [35]:
ar1=np.array([8,5,6,4,2,4,9,7,3])
ar1

array([8, 5, 6, 4, 2, 4, 9, 7, 3])

In [36]:
ar2=ar1[4:6]

In [37]:
ar2

array([2, 4])

In [38]:
ar2=ar1[2:5]
ar2

array([6, 4, 2])

In [39]:
ar1=[1,2,3,4,5,6,7,8]
ar2=ar1[2:4]
ar2

[3, 4]